"""Document formatters for onboarding docs (Markdown, HTML, JSON)."""

from __future__ import annotations

import json
from datetime import datetime, timezone

from .models import FindingType, OnboardingDoc, OnboardingSection

FINDING_TYPE_EMOJI = {
    FindingType.ARCHITECTURAL_DECISION: "🏗️",
    FindingType.WORKAROUND: "🔧",
    FindingType.TECHNICAL_DEBT: "💳",
    FindingType.LEGACY_CODE: "📜",
    FindingType.SECURITY_CHANGE: "🔒",
    FindingType.PERFORMANCE_CHOICE: "⚡",
    FindingType.NAMING_MYSTERY: "❓",
    FindingType.ANOMALY: "⚠️",
}


def generate_markdown(doc: OnboardingDoc) -> str:
    """Generate a Markdown onboarding document."""
    lines: list[str] = []

    lines.append(f"# Onboarding Guide: {doc.project_name}")
    lines.append("")
    lines.append(f"**Generated**: {doc.generated_at}")
    lines.append(f"**Findings Analyzed**: {doc.total_findings}")
    lines.append("")

    if doc.overview:
        lines.append("## Overview")
        lines.append("")
        lines.append(doc.overview)
        lines.append("")

    if doc.architecture_summary:
        lines.append("## Architecture Summary")
        lines.append("")
        lines.append(doc.architecture_summary)
        lines.append("")

    if doc.key_files:
        lines.append("## Key Files")
        lines.append("")
        for f in doc.key_files:
            lines.append(f"- `{f}`")
        lines.append("")

    if doc.sections:
        lines.append("---")
        lines.append("")
        lines.append("## Code Explanations")
        lines.append("")

        # Group sections by type
        by_type: dict[FindingType, list[OnboardingSection]] = {}
        for section in doc.sections:
            by_type.setdefault(section.finding_type, []).append(section)

        for finding_type, sections in by_type.items():
            emoji = FINDING_TYPE_EMOJI.get(finding_type, "📌")
            lines.append(f"### {emoji} {finding_type.value.replace('_', ' ').title()}")
            lines.append("")

            for section in sections:
                lines.extend(_section_to_markdown(section))
                lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by [Codebase Onboarding Doc](https://github.com/tomocchi1029/codebase-onboarding-doc)*")
    lines.append("")

    return "\n".join(lines)


def _section_to_markdown(section: OnboardingSection) -> list[str]:
    """Convert a single section to markdown."""
    lines: list[str] = []

    lines.append(f"#### {section.title}")
    lines.append("")
    if section.confidence > 0:
        lines.append(f"*Confidence: {section.confidence:.0%}*")
        lines.append("")

    if section.file_path:
        loc = f"`{section.file_path}`"
        if section.code_snippet:
            loc += f" — line {section.file_path}"
        lines.append(f"**Location**: {loc}")
        lines.append("")

    if section.explanation:
        lines.append(section.explanation)
        lines.append("")

    if section.code_snippet:
        lines.append("```python")
        lines.append(section.code_snippet)
        lines.append("```")
        lines.append("")

    if section.commit_history:
        lines.append("**History**:")
        lines.append("")
        lines.append(section.commit_history)
        lines.append("")

    if section.impact:
        lines.append("**Impact for new developers**:")
        lines.append("")
        lines.append(section.impact)
        lines.append("")

    if section.warnings:
        lines.append("**⚠️ Warnings**:")
        lines.append("")
        for w in section.warnings:
            lines.append(f"- {w}")
        lines.append("")

    return lines


def generate_json(doc: OnboardingDoc) -> str:
    """Generate JSON output."""
    return json.dumps(doc.model_dump(), indent=2, ensure_ascii=False, default=str)


def generate_html(doc: OnboardingDoc) -> str:
    """Generate a self-contained HTML onboarding document."""
    sections_html: list[str] = []

    # Group by type
    by_type: dict[FindingType, list[OnboardingSection]] = {}
    for section in doc.sections:
        by_type.setdefault(section.finding_type, []).append(section)

    for finding_type, sections in by_type.items():
        emoji = FINDING_TYPE_EMOJI.get(finding_type, "📌")
        type_name = finding_type.value.replace("_", " ").title()

        section_items = ""
        for s in sections:
            warnings_html = ""
            if s.warnings:
                warnings_items = "".join(f"<li>{w}</li>" for w in s.warnings)
                warnings_html = f'<div class="warnings"><h4>⚠️ Warnings</h4><ul>{warnings_items}</ul></div>'

            code_html = ""
            if s.code_snippet:
                code_html = f'<pre><code>{s.code_snippet}</code></pre>'

            confidence_html = ""
            if s.confidence > 0:
                confidence_html = f'<span class="confidence">Confidence: {s.confidence:.0%}</span>'

            section_items += f"""
            <div class="section">
                <h4>{s.title} {confidence_html}</h4>
                {f'<p class="location">📍 <code>{s.file_path}</code></p>' if s.file_path else ''}
                <p>{s.explanation}</p>
                {code_html}
                {f'<div class="impact"><h4>Impact</h4><p>{s.impact}</p></div>' if s.impact else ''}
                {warnings_html}
            </div>"""

        sections_html.append(f"""
        <div class="finding-group">
            <h3>{emoji} {type_name}</h3>
            {section_items}
        </div>""")

    key_files_html = ""
    if doc.key_files:
        items = "".join(f"<li><code>{f}</code></li>" for f in doc.key_files)
        key_files_html = f'<div class="key-files"><h2>Key Files</h2><ul>{items}</ul></div>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Onboarding Guide: {doc.project_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; background: #0d1117; color: #c9d1d9; }}
        h1 {{ color: #f0f6fc; border-bottom: 1px solid #30363d; padding-bottom: 0.5rem; }}
        h2 {{ color: #f0f6fc; margin-top: 2rem; }}
        h3 {{ color: #d2a8ff; }}
        h4 {{ color: #79c0ff; margin-bottom: 0.25rem; }}
        .meta {{ color: #8b949e; font-size: 0.9rem; margin-bottom: 1rem; }}
        .confidence {{ color: #8b949e; font-size: 0.85rem; font-weight: normal; }}
        .location {{ color: #8b949e; font-size: 0.85rem; }}
        .finding-group {{ background: #161b22; border-radius: 8px; padding: 1rem 1.5rem; margin: 1rem 0; }}
        .section {{ background: #0d1117; border-radius: 6px; padding: 0.75rem 1rem; margin: 0.5rem 0; border-left: 3px solid #30363d; }}
        .impact {{ background: #161b22; border-radius: 6px; padding: 0.5rem 1rem; margin-top: 0.5rem; }}
        .warnings {{ background: #2d1b1b; border-radius: 6px; padding: 0.5rem 1rem; margin-top: 0.5rem; border-left: 3px solid #f85149; }}
        .warnings ul {{ margin: 0.5rem 0; padding-left: 1.5rem; }}
        .key-files ul {{ list-style: none; padding: 0; }}
        .key-files li {{ margin: 0.25rem 0; }}
        pre {{ background: #161b22; border-radius: 6px; padding: 0.75rem; overflow-x: auto; }}
        code {{ background: #30363d; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }}
        pre code {{ background: none; padding: 0; }}
        .footer {{ margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #30363d; color: #8b949e; font-size: 0.85rem; }}
    </style>
</head>
<body>
    <h1>Onboarding Guide: {doc.project_name}</h1>
    <div class="meta">
        <p>Generated: {doc.generated_at} | Findings: {doc.total_findings}</p>
    </div>
    {f'<h2>Overview</h2><p>{doc.overview}</p>' if doc.overview else ''}
    {f'<h2>Architecture Summary</h2><p>{doc.architecture_summary}</p>' if doc.architecture_summary else ''}
    {key_files_html}
    <h2>Code Explanations</h2>
    {''.join(sections_html)}
    <div class="footer">
        <p>Generated by <a href="https://github.com/tomocchi1029/codebase-onboarding-doc">Codebase Onboarding Doc</a></p>
    </div>
</body>
</html>"""
