"""Data models for codebase onboarding documentation."""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class FindingType(str, Enum):
    ARCHITECTURAL_DECISION = "architectural_decision"
    WORKAROUND = "workaround"
    TECHNICAL_DEBT = "technical_debt"
    LEGACY_CODE = "legacy_code"
    SECURITY_CHANGE = "security_change"
    PERFORMANCE_CHOICE = "performance_choice"
    NAMING_MYSTERY = "naming_mystery"
    ANOMALY = "anomaly"


class CommitInfo(BaseModel):
    """Information about a git commit."""

    hash: str
    author: str = ""
    date: str = ""
    message: str = ""
    files_changed: list[str] = Field(default_factory=list)


class CodeFinding(BaseModel):
    """A notable finding in the codebase that needs a 'why' explanation."""

    id: str
    finding_type: FindingType
    title: str
    file_path: str
    line_start: int | None = None
    line_end: int | None = None
    code_snippet: str = ""
    related_commits: list[CommitInfo] = Field(default_factory=list)
    description: str = ""
    tags: list[str] = Field(default_factory=list)


class OnboardingSection(BaseModel):
    """A section in the onboarding document."""

    title: str
    finding_type: FindingType
    explanation: str = Field("", description="The 'why' explanation generated by LLM")
    code_snippet: str = ""
    file_path: str = ""
    commit_history: str = ""
    impact: str = Field("", description="What this means for new developers")
    warnings: list[str] = Field(default_factory=list, description="Things to watch out for")
    confidence: float = Field(0.5, ge=0.0, le=1.0)


class OnboardingDoc(BaseModel):
    """The complete onboarding document."""

    project_name: str
    overview: str = ""
    architecture_summary: str = ""
    sections: list[OnboardingSection] = Field(default_factory=list)
    key_files: list[str] = Field(default_factory=list)
    generated_at: str = ""
    total_findings: int = 0
